# Generated by Django 5.2.3 on 2025-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcGbp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('volumefrom', models.FloatField(blank=True, null=True)),
                ('volumeto', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('conversiontype', models.TextField(blank=True, db_column='conversionType', null=True)),
                ('conversionsymbol', models.TextField(blank=True, db_column='conversionSymbol', null=True)),
            ],
            options={
                'db_table': 'btc_gbp',
                'managed': True,
            },
        ),
    ]
