# Generated by Django 5.2.3 on 2025-07-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code', models.CharField(max_length=10)),
                ('quote_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'currency_pair',
                'unique_together': {('base_code', 'quote_code')},
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_name', models.CharField(default='unknown', max_length=7)),
                ('timestamp', models.BigIntegerField()),
                ('open', models.DecimalField(decimal_places=3, max_digits=18)),
                ('high', models.DecimalField(decimal_places=3, max_digits=18)),
                ('low', models.DecimalField(decimal_places=3, max_digits=18)),
                ('close', models.DecimalField(decimal_places=3, max_digits=18)),
                ('volumeFrom', models.DecimalField(decimal_places=3, max_digits=30)),
                ('volumeTo', models.DecimalField(decimal_places=3, max_digits=30)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currencypair')),
            ],
            options={
                'db_table': 'ohlcv_hourly',
                'indexes': [models.Index(fields=['pair', '-timestamp'], name='ohlcv_hourl_pair_id_c6a239_idx')],
                'unique_together': {('pair', 'timestamp')},
            },
        ),
    ]
