# Generated by Django 5.2.3 on 2025-07-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btcgbp',
            options={'managed': True},
        ),
    ]
