# Generated by Django 5.2.3 on 2025-07-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btcgbp',
            old_name='conversionsymbol',
            new_name='conversionSymbol',
        ),
        migrations.RenameField(
            model_name='btcgbp',
            old_name='conversiontype',
            new_name='conversionType',
        ),
    ]
