# Generated by Django 5.2.3 on 2025-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_btcgbp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcgbp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
